### ISSUE TITLE
lien vers www.chimiegenerale.ch cassé

### ISSUE THREAD

**Issue by briner** [mrizzello/chimie-generale#4]
Bonjour,

pour information lorsqu’on se rend sur le site : https://chimiegenerale.ch, le premier lien www.chimiegenerale.ch pointe vers www.chimiegenerale.ch/www.chimiegenerale.ch qui est un page "not found"

De plus, je n’ai pas trouvé le lien vers le epub.

cED

**Comment by mrizzello** [comment]
Bonjour,

Merci pour votre commentaire et désolé pour le retard dans ma réponse.

- Les problèmes de redirection ont été résolus il y quelque temps.
- La version epub n'est plus disponible car la mise en page n'est pas respectée dans ce format. Le format epub gère mal l'affichage de tableaux complexes, d'équations et autres éléments graphique utilisés dans ce book.
