### ISSUE TITLE
Légende figure 8.7 - "Entre" ou "au sein"

### ISSUE THREAD

**Issue by a-humble-contribution** [mrizzello/chimie-generale#5]
Bonjour, même si les schémas de la figure 8.7 sont très clairs, je trouve que les termes de la légende "au sein de molécules d'eau" peuvent prêter à confusion et suggérer des liaisons intramoléculaires plutôt qu'intermoléculaires - spécialement pour les élèves novices.

Pourquoi ne pas dire "Liaison hydrogène entre des molécules d’eau" à la place?

**Comment by mrizzello** [comment]
Merci pour cette suggestion. La légende est devenue : "La liaison hydrogène entre les molécules d’eau".
